version: 0.0
os: linux
files:
  - source: /config.ru
    destination: /home/ubuntu/ruby-on-rails
    overwrite: true
  - source: /Gemfile
    destination: /home/ubuntu/ruby-on-rails
    overwrite: true
  - source: /Gemfile.lock
    destination: /home/ubuntu/ruby-on-rails
    overwrite: true
  - source: /Rakefile
    destination: /home/ubuntu/ruby-on-rails
    overwrite: true
  - source: /README.md
    destination: /home/ubuntu/ruby-on-rails
    overwrite: true
  - source: /app/
    destination: /home/ubuntu/ruby-on-rails/app
    overwrite: true
  - source: /config/
    destination: /home/ubuntu/ruby-on-rails/config
    overwrite: true
  - source: /db/
    destination: /home/ubuntu/ruby-on-rails/db
    overwrite: true
  - source: /log/
    destination: /home/ubuntu/ruby-on-rails/log
    overwrite: true
  - source: /vendor/
    destination: /home/ubuntu/ruby-on-rails/vendor
    overwrite: true
  - source: /public/
    destination: /home/ubuntu/ruby-on-rails/public
    overwrite: true
  - source: /test/
    destination: /home/ubuntu/ruby-on-rails/test
    overwrite: true
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 1800
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
